version: '3'
services:
  flask:
    build: ./flaskApp

    container_name: flask-app

    restart: on-failure
    
    ports:
      - "8080:8080"

    depends_on:
     - redis

  redis:
    image: redis:alpine

    container_name: redis-db
